### ISSUE TITLE
Apple Silicon Support

### ISSUE THREAD

**Issue by fishcharlie** [TylerBrock/saw#71]
Any chance we could get support for a native Apple Silicon binary?

**Comment by TylerBrock** [comment]
Great idea. The next time I have a moment to work on this project I will try to create an arm64 build.

**Comment by a-h** [comment]
I took a look at this, and it looks like the `.goreleaser` project is already properly configured for Apple Silicon: https://github.com/TylerBrock/saw/blob/master/.goreleaser.yml

The `circle.yml` build process is using the latest `golang:alpine` build, and the latest version of `goreleaser` on each build. Go added support for ARM64 Macs in https://go.dev/doc/go1.16 - and `goreleaser` supports it, so I think it's just a case of getting a new build out.

To do this, I think the `circle.yml` needs updating since it's currently giving an error of `required key [jobs] not found`. I think it's a change made by Circle CI migrating to a new (V2) syntax, rather than anything changed in this repo.

But FWIW, you can install `saw` from source on my M1 Mac with `go install github.com/TylerBrock/saw@latest`
